---
name: tests

on:
  push:
    branches-ignore:
    - 'development/**'

env:
  GOFLAGS: -mod=vendor

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -cover --count 1 ./...

  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.45.0
        only-new-issues: true
